### ISSUE TITLE
Customized color?

### ISSUE THREAD

**Issue by LXXXXR** [wookayin/gpustat#119] opened 2022-04-25 09:16 UTC
Thank you for such a handy tool!

I just have a question about customizing color.
I'm using the newest version of gpustat. But when I use command `gpustat --watch -u -c`, I can not see the username because it is set to black I guess. Please see the attached screenshot.
<img width="683" alt="Screenshot 2022-04-25 at 5 09 26 PM" src="https://user-images.githubusercontent.com/73265258/165058420-00f1feb9-4d4f-4135-8542-da635ca4608b.png">

On the other hand, when I add `--no-color`, it works just fine. But I do want colorful display and username at the same time. So I was wondering if there's any ways to customize the color myself. Thank you very much

**Comment by wookayin** [comment] 2022-07-04 10:11
Duplicate of #9 and #51. Sorry, I'll try to implement the feature sometime soon..

**Closed by wookayin** 2022-07-04 10:11 UTC
Labels: new feature, contributions welcome
