### ISSUE TITLE
[BUG] Font Color Display Problem

### ISSUE THREAD

**Issue by shaonianruntu** [wookayin/gpustat#111] opened 2021-12-13 03:52 UTC
There are some color display problem of `gpustat`, as show as below: 

![145749576-ea38fc45-0480-4a24-9010-156193a35232](https://user-images.githubusercontent.com/16336682/167794027-6bb4d128-27ad-485a-8dcd-29425e2e22e9.png)

![2022-05-11 at 15 31 59](https://user-images.githubusercontent.com/16336682/167793892-48066fc8-f2b5-4405-ba39-6aee84bb2a18.jpg)

![截屏2021-12-13 at 11 53 15](https://user-images.githubusercontent.com/16336682/145749783-96c2afc8-ba6c-4734-8162-a9337d2b203a.png)

**Comment by Yevgnen** [comment] 2022-01-21 03:35
Same issue here.

**Comment by wookayin** [comment] 2022-06-07 03:29
This is a duplicate of #9.

**Closed by wookayin** 2022-06-07 03:29 UTC
